
all:
	javac -classpath /home/NOSQL/FEL-B4M36DS2/mapreduce/hadoop-common-3.1.1.jar:/home/NOSQL/FEL-B4M36DS2/mapreduce/hadoop-mapreduce-client-core-3.1.1.jar -d classes/ MapReduce.java
	jar -cvf MapReduce.jar -C classes/ .
